import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

// import "keen-slider/keen-slider.min.css";
import Banner from "./components/banner";

const roboto = Roboto({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <title>Karen Rodrigues Sobrancelhas</title>
      </head>
      <body className={roboto.className}>
        <Banner />
        {children}
      </body>
    </html>
  );
}
